version: '3'

services:
  dind-container:
    image: dind:latest
    container_name: proccess_conntainer
    ports:
      - "8080:80"
    networks:
      - my_network
  
  celery-container:
    image: holder:latest
    container_name: holder_container
    ports:
      - "3306:3306"
    networks:
      - my_network

  redis-container:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
